CREATE USER admin password admin WITH LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION; GRANT postgres TO admin;
ALTER USER <user_name> PASSWORD '<new_password>';


CREATE DATABASE DevRock WITH OWNER = postgres ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;
