# Generated by Django 2.1.4 on 2019-02-04 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=160)),
                ('body', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'ToDo'), (1, 'InProgress'), (2, 'Review'), (3, 'Done')], default=0)),
                ('project', models.TextField(default='Нет', null=True, verbose_name='choices=get_all_projects_enumerated()')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
