# Generated by Django 2.1.4 on 2019-02-17 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0002_auto_20190211_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'To do'), (1, 'In progress'), (2, 'Done'), (3, 'On review')], default=0),
        ),
    ]
