# Generated by Django 2.1.4 on 2019-02-17 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_auto_20190217_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
    ]
