# Generated by Django 2.1.4 on 2019-02-06 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя файла')),
                ('file', models.FileField(null=True, upload_to='files/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл страницы',
                'verbose_name_plural': 'Файлы страницы',
            },
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя файла')),
                ('file', models.FileField(null=True, upload_to='files/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл проекта',
                'verbose_name_plural': 'Файлы проекта',
            },
        ),
        migrations.CreateModel(
            name='ProjectPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_page', models.IntegerField(blank=True, null=True, verbose_name='Родительская страница')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainimg', models.ImageField(blank=True, null=True, upload_to='mezzanine/MainImg')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='slug')),
                ('ended', models.BooleanField(blank=True, null=True, verbose_name='Готовность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='projectpages',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mezzanine.Projects', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='projectpages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mezzanine.Projects', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AddField(
            model_name='pagefiles',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mezzanine.ProjectPages', verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='pagefiles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
    ]
