# Generated by Django 2.1.4 on 2019-03-18 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mezzanine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevComand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Разработчик')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectpages',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='slug',
        ),
        migrations.AddField(
            model_name='devcomand',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mezzanine.Projects', verbose_name='Проект'),
        ),
    ]
