# Generated by Django 2.1.4 on 2019-03-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine', '0002_auto_20190318_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devcomand',
            name='developers',
        ),
        migrations.RemoveField(
            model_name='devcomand',
            name='project',
        ),
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='mainimg',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='mezzanine/MainImg'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Заголовок'),
        ),
        migrations.DeleteModel(
            name='DevComand',
        ),
    ]
