# Generated by Django 2.1.4 on 2019-01-22 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mezzanine', '0002_auto_20190122_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
        migrations.RenameModel(
            old_name='ProjectPage',
            new_name='ProjectPages',
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
