# Generated by Django 2.1.4 on 2019-01-22 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mezzanine', '0003_auto_20190122_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/', verbose_name='Файл')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mezzanine.ProjectPages', verbose_name='Страница')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл страницы',
                'verbose_name_plural': 'Файлы страницы',
            },
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='files/', verbose_name='Файл')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mezzanine.Projects', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл проекта',
                'verbose_name_plural': 'Файлы проекта',
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='page',
        ),
        migrations.RemoveField(
            model_name='file',
            name='project',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
