# Generated by Django 2.1.4 on 2019-01-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine', '0004_auto_20190122_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagefiles',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя файла'),
        ),
    ]
