# Generated by Django 2.1.4 on 2019-01-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine', '0005_auto_20190123_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='mainimg',
            field=models.ImageField(blank=True, null=True, upload_to='mezzanine/MainImg'),
        ),
    ]
