# Generated by Django 2.1.4 on 2019-01-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine', '0006_auto_20190123_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpages',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True, verbose_name='slug'),
        ),
    ]
