# Generated by Django 2.1.4 on 2019-01-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine', '0007_auto_20190124_0432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpages',
            options={'ordering': ['title'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['title'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='projectpages',
            name='parent_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='Родительская страница'),
        ),
    ]
