# Generated by Django 2.1.4 on 2019-01-30 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine', '0008_auto_20190125_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='ended',
            field=models.BooleanField(blank=True, null=True, verbose_name='Готовность'),
        ),
        migrations.AlterField(
            model_name='pagefiles',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='projectpages',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mezzanine.Projects', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='projectpages',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
