# Generated by Django 2.1.4 on 2019-01-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine', '0009_auto_20190131_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpages',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уровень наследования'),
        ),
    ]
