# Generated by Django 2.1.4 on 2019-03-19 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя пользователя')),
                ('family', models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия пользователя')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('avatar', models.ImageField(blank=True, max_length=256, null=True, upload_to='mezzanine/MainImg')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['family', 'name', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Tehnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tehno', models.CharField(max_length=25, verbose_name='Технология')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['tehno'],
            },
        ),
        migrations.CreateModel(
            name='TehnologyGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=25, verbose_name='Группа технологий')),
            ],
            options={
                'verbose_name': 'Группа технологий',
                'verbose_name_plural': 'Группы технологий',
                'ordering': ['group'],
            },
        ),
        migrations.AddField(
            model_name='tehnology',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.TehnologyGroups', verbose_name='Группа технологий'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stack',
            field=models.ManyToManyField(to='user_profiles.Tehnology', verbose_name='Стэк технологий'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
